const jCategory = [
    {
        index: 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "01",
        hours: "50h/week",
        description:"It is a long-established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using “Content here, content here,” making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for “lorem ipsum” will uncover many websites still in their infancy. Various versions have evolved over the years, sometimes on purpose (injected humour and the like).",
        workplace: "Work From Home",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "1 to 5 years of experience in web development",

    },
     {
        index: 1,
        image: "../images/uber.png",
        title: "Business Associate",
        rate: "$900-1200/m",
        av: "Part Time",
        companyName: "Uber",
        location: "USA",
        vacancy: "01",
        hours: "50h/week",
        description:"We are seeking a motivated and detail-oriented Business Associate to support our business operations, strategy, and client relations. The ideal candidate will assist in driving growth initiatives, managing data and reports, coordinating with cross-functional teams, and ensuring smooth execution of day-to-day business activities.",
        workplace: "Work From Home",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "1 to 3 years of experience in web development",
    },
    {
        index: 2,
        image: "../images/apple.png",
        title: "Software Developer",
        rate: "$1000-1200/m",
        av: "Full Time",
        companyName: "Apple",
        location: "USA",
        vacancy: "05",
        hours: "40h/week",
        description:"We are looking for a passionate and skilled Software Developer to design, develop, and maintain high-quality software applications. The ideal candidate should have strong programming skills, a problem-solving mindset, and the ability to work collaboratively in an agile environment.",
        workplace: "Office",
        education: "Bachelor's degree in Computer Science",
        experience: "0 to 3 years of experience in web development",
    },
    {
        index: 3,
        image: "../images/facebook.png",
        title: "Python Developer",
        rate: "$700-1100/m",
        av: "Part Time",
        companyName: "Facebook",
        location: "India",
        vacancy: "01",
        hours: "48h/week",
        description:"We are looking for a skilled and motivated Python Developer to design, develop, and maintain scalable backend systems and web applications. The ideal candidate will have a strong understanding of Python frameworks, RESTful APIs, and database management, along with a passion for clean, efficient, and well-documented code.",
        workplace: "Work From Home",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "Freshers",
    },
    {
        index: 4,
        image: "../images/linkedin.png",
        title: "React Developer",
        rate: "$1100-1400/m",
        av: "Full Time",
        companyName: "Linkedin",
        location: "Bengalore",
        vacancy: "03",
        hours: "48h/week",
        description:"We are looking for a talented React Developer to build and maintain dynamic, responsive, and high-performance web applications. The ideal candidate will have hands-on experience with React.js, strong UI/UX understanding, and the ability to collaborate effectively with backend developers and designers.",
        workplace: "Office",
        education: "Bachelor's degree in Computer Science or It field",
        experience: "1 to 2 years of experience in web development",
    },
    {
        index: 5,
        image: "../images/instagram.png",
        title: "Software Developer Intern",
        rate: "$800-1200/m",
        av: "Part Time",
        companyName: "Instagram",
        location: "India",
        vacancy: "05",
        hours: "50h/week",
        description:"We are looking for a motivated Software Developer Intern to assist our development team in designing, developing, and testing software applications. This internship provides hands-on experience with real-world projects, coding best practices, and collaboration in an agile environment.",
        workplace: "Work From Home",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "0 to 2 years of experience in web development or Freshers",
    },
    {
        index: 6,
        image: "../images/yahoo.png",
        title: "Backend Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Yahoo",
        location: "India",
        vacancy: "08",
        hours: "50h/week",
        description:"We are looking for a skilled Backend Developer to design, develop, and maintain server-side logic, databases, and APIs for our applications. The ideal candidate should have strong programming skills, experience with backend frameworks, and the ability to work collaboratively with frontend developers and other teams to deliver robust and scalable software solutions.",
        workplace: "Office",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "Freshers only eligible",
    },
    {
        index: 7,
        image: "../images/wordpress.png",
        title: "Full Stack Web Developer",
        rate: "$1100-1900/m",
        av: "Full Time",
        companyName: "Wordpress",
        location: "USA",
        vacancy: "01",
        hours: "50h/week",
        description:"We are seeking a talented Full Stack Web Developer to design, develop, and maintain both frontend and backend components of web applications. The ideal candidate will have hands-on experience with modern web technologies, strong problem-solving skills, and the ability to work collaboratively with cross-functional teams to deliver high-quality software solutions.",
        workplace: "Work From Home",
        education: "Bachelor's degree in Computer Science or Electronics field",
        experience: "3 to 5 years of experience in web development",
    },
];